In [1]:
import pandas as pd
import polars as pl
import os

In [2]:
# Read tracker CSV in for data filtering and cleansing
directory = r'C:\Users\gfoley\Downloads'
filename = 'ibtracs.NA.list.v04r01.csv'

# Create the full file path
file_path = os.path.join(directory, filename)

# Load the CSV file into a Polars DataFrame
tracker_df = pl.read_csv(file_path)
tracker_df.head()

shape: (5, 174)
┌──────────────┬────────┬────────┬───────┬───┬─────────────┬─────────────┬─────────────┬───────────┐
│ SID          ┆ SEASON ┆ NUMBER ┆ BASIN ┆ … ┆ USA_SEARAD_ ┆ USA_SEARAD_ ┆ STORM_SPEED ┆ STORM_DIR │
│ ---          ┆ ---    ┆ ---    ┆ ---   ┆   ┆ SW          ┆ NW          ┆ ---         ┆ ---       │
│ str          ┆ str    ┆ str    ┆ str   ┆   ┆ ---         ┆ ---         ┆ str         ┆ str       │
│              ┆        ┆        ┆       ┆   ┆ str         ┆ str         ┆             ┆           │
╞══════════════╪════════╪════════╪═══════╪═══╪═════════════╪═════════════╪═════════════╪═══════════╡
│              ┆ Year   ┆        ┆       ┆ … ┆ nmile       ┆ nmile       ┆ kts         ┆ degrees   │
│ 1851175N2627 ┆ 1851   ┆ 5      ┆ NA    ┆ … ┆             ┆             ┆ 6           ┆ 290       │
│ 0            ┆        ┆        ┆       ┆   ┆             ┆             ┆             ┆           │
│ 1851175N2627 ┆ 1851   ┆ 5      ┆ NA    ┆ … ┆             ┆             ┆ 6           ┆ 290       │
│ 0            ┆        ┆        ┆       ┆   ┆             ┆             ┆             ┆           │
│ 1851175N2627 ┆ 1851   ┆ 5      ┆ NA    ┆ … ┆             ┆             ┆ 6           ┆ 290       │
│ 0            ┆        ┆        ┆       ┆   ┆             ┆             ┆             ┆           │
│ 1851175N2627 ┆ 1851   ┆ 5      ┆ NA    ┆ … ┆             ┆             ┆ 6           ┆ 290       │
│ 0            ┆        ┆        ┆       ┆   ┆             ┆             ┆             ┆           │
└──────────────┴────────┴────────┴───────┴───┴─────────────┴─────────────┴─────────────┴───────────┘

In [3]:
# Convert Polars DataFrame to pandas DataFrame
tracker_df = tracker_df.to_pandas()

In [4]:
# Remove unnecessary columns for hurricane analysis, many of these are empty due to regionality
columns_to_remove = [
    'TOKYO_LAT', 'TOKYO_LON', 'TOKYO_GRADE', 'TOKYO_WIND', 'TOKYO_PRES',
    'TOKYO_R50_DIR', 'TOKYO_R50_LONG', 'TOKYO_R50_SHORT', 'TOKYO_R30_DIR',
    'TOKYO_R30_LONG', 'TOKYO_R30_SHORT', 'TOKYO_LAND', 'CMA_LAT', 'CMA_LON',
    'CMA_CAT', 'CMA_WIND', 'CMA_PRES', 'HKO_LAT', 'HKO_LON', 'HKO_CAT',
    'HKO_WIND', 'HKO_PRES', 'KMA_LAT', 'KMA_LON', 'KMA_CAT', 'KMA_WIND',
    'KMA_PRES', 'KMA_R50_DIR', 'KMA_R50_LONG', 'KMA_R50_SHORT', 'KMA_R30_DIR',
    'KMA_R30_LONG', 'KMA_R30_SHORT', 'NEWDELHI_LAT', 'NEWDELHI_LON',
    'NEWDELHI_GRADE', 'NEWDELHI_WIND', 'NEWDELHI_PRES', 'NEWDELHI_CI',
    'NEWDELHI_DP', 'NEWDELHI_POCI', 'REUNION_LAT', 'REUNION_LON',
    'REUNION_TYPE', 'REUNION_WIND', 'REUNION_PRES', 'REUNION_TNUM',
    'REUNION_CI', 'REUNION_RMW', 'REUNION_R34_NE', 'REUNION_R34_SE',
    'REUNION_R34_SW', 'REUNION_R34_NW', 'REUNION_R50_NE', 'REUNION_R50_SE',
    'REUNION_R50_SW', 'REUNION_R50_NW', 'REUNION_R64_NE', 'REUNION_R64_SE',
    'REUNION_R64_SW', 'REUNION_R64_NW', 'BOM_LAT', 'BOM_LON', 'BOM_TYPE',
    'BOM_WIND', 'BOM_PRES', 'BOM_TNUM', 'BOM_CI', 'BOM_RMW', 'BOM_R34_NE',
    'BOM_R34_SE', 'BOM_R34_SW', 'BOM_R34_NW', 'BOM_R50_NE', 'BOM_R50_SE',
    'BOM_R50_SW', 'BOM_R50_NW', 'BOM_R64_NE', 'BOM_R64_SE', 'BOM_R64_SW',
    'BOM_R64_NW', 'BOM_ROCI', 'BOM_POCI', 'BOM_EYE', 'BOM_POS_METHOD',
    'BOM_PRES_METHOD', 'NADI_LAT', 'NADI_LON', 'NADI_CAT', 'NADI_WIND',
    'NADI_PRES', 'WELLINGTON_LAT', 'WELLINGTON_LON', 'WELLINGTON_WIND',
    'WELLINGTON_PRES', 'NEUMANN_LAT', 'NEUMANN_LON', 'NEUMANN_CLASS',
    'NEUMANN_WIND', 'NEUMANN_PRES', 'MLC_LAT', 'MLC_LON', 'MLC_CLASS',
    'MLC_WIND', 'MLC_PRES', 'USA_GUST', 'BOM_GUST', 'BOM_GUST_PER',
    'REUNION_GUST', 'REUNION_GUST_PER'
]

tracker_df = tracker_df.drop(columns=columns_to_remove)

In [5]:
# Create list of most intense hurricanes provided by clean_hurricane_data
major_canes = [
    'EASY', 'KING', 'CAROL', 'HAZEL', 'AUDREY', 'HELENE', 'GRACIE',
    'DONNA', 'CARLA', 'BETSY', 'BETSY', 'ALMA', 'BEULAH', 'CAMILLE',
    'CELIA', 'ALICIA', 'ELENA', 'HUGO', 'ANDREW', 'ANDREW', 'EMILY',
    'OPAL', 'FRAN', 'BRET', 'CHARLEY', 'IVAN', 'JEANNE', 'DENNIS',
    'KATRINA', 'RITA', 'WILMA', 'HARVEY', 'IRMA', 'MICHAEL', 'LAURA',
    'ZETA', 'IDA', 'IAN', 'IDALIA'
]
len(major_canes)

# Remove rows where the 'NAME' column does not match any of the specified major canes
tracker_df = tracker_df[tracker_df['NAME'].str.upper().isin(major_canes)]

In [6]:
# Review how many major_canes there are
len(major_canes)

39

In [7]:
# List major_cane names
major_canes

['EASY',
 'KING',
 'CAROL',
 'HAZEL',
 'AUDREY',
 'HELENE',
 'GRACIE',
 'DONNA',
 'CARLA',
 'BETSY',
 'BETSY',
 'ALMA',
 'BEULAH',
 'CAMILLE',
 'CELIA',
 'ALICIA',
 'ELENA',
 'HUGO',
 'ANDREW',
 'ANDREW',
 'EMILY',
 'OPAL',
 'FRAN',
 'BRET',
 'CHARLEY',
 'IVAN',
 'JEANNE',
 'DENNIS',
 'KATRINA',
 'RITA',
 'WILMA',
 'HARVEY',
 'IRMA',
 'MICHAEL',
 'LAURA',
 'ZETA',
 'IDA',
 'IAN',
 'IDALIA']

In [8]:
# Review unique hurricane names in tracker_df to ensure names are the same
tracker_canes = tracker_df['NAME'].unique()
print(tracker_canes)

['EASY' 'KING' 'CAROL' 'HAZEL' 'BETSY' 'CARLA' 'AUDREY' 'ALMA' 'HELENE'
 'BEULAH' 'GRACIE' 'DONNA' 'CELIA' 'ELENA' 'CAMILLE' 'LAURA' 'FRAN' 'IRMA'
 'CHARLEY' 'IVAN' 'JEANNE' 'BRET' 'DENNIS' 'EMILY' 'HARVEY' 'KATRINA'
 'ALICIA' 'ANDREW' 'HUGO' 'OPAL' 'MICHAEL' 'RITA' 'WILMA' 'ZETA' 'IDA'
 'IAN' 'IDALIA']

In [9]:
# Review tracker_cane names to ensure matching with major_canes
len(tracker_canes)

37

Note: Betsy and Andrew are listed twice in major_canes due to NOAA adjustment of CAT or multiple landfalls within the same storm system

In [10]:
# Perform value counts on the 'Name' column
value_counts = tracker_df['NAME'].value_counts()
print(value_counts)

NAME
HELENE     556
EMILY      512
DENNIS     497
HARVEY     380
BETSY      355
BEULAH     341
IVAN       339
CHARLEY    314
BRET       308
JEANNE     308
CAROL      296
ALMA       251
FRAN       247
IDA        235
LAURA      223
EASY       223
MICHAEL    200
CELIA      199
CARLA      193
HAZEL      183
ELENA      154
IRMA       150
DONNA      135
KATRINA    134
ANDREW     128
HUGO       124
ZETA       117
IAN        115
IDALIA     104
GRACIE      98
WILMA       92
OPAL        75
CAMILLE     71
RITA        68
KING        59
ALICIA      48
AUDREY      38
Name: count, dtype: int64

In [11]:
tracker_df = tracker_df.sort_values(by='ISO_TIME')
tracker_df

,SID,SEASON,NUMBER,BASIN,SUBBASIN,NAME,ISO_TIME,NATURE,LAT,LON,...,TD9635_WIND,TD9635_PRES,TD9635_ROCI,USA_SEAHGT,USA_SEARAD_NE,USA_SEARAD_SE,USA_SEARAD_SW,USA_SEARAD_NW,STORM_SPEED,STORM_DIR
61773,1950244N20277,1950,68,NA,CS,EASY,1950-09-01 06:00:00,TS,19.7,-83.2,...,,,,,,,,,2,0
61774,1950244N20277,1950,68,NA,CS,EASY,1950-09-01 09:00:00,TS,19.8,-83.2,...,,,,,,,,,2,10
61775,1950244N20277,1950,68,NA,CS,EASY,1950-09-01 12:00:00,TS,19.9,-83.2,...,,,,,,,,,2,10
61776,1950244N20277,1950,68,NA,CS,EASY,1950-09-01 15:00:00,TS,20.0,-83.2,...,,,,,,,,,2,10
61777,1950244N20277,1950,68,NA,CS,EASY,1950-09-01 18:00:00,TS,20.1,-83.2,...,,,,,,,,,2,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125107,2023239N21274,2023,51,NA,NA,IDALIA,2023-09-07 18:00:00,ET,43.6,-60.1,...,,,,,,,,,8,50
125108,2023239N21274,2023,51,NA,NA,IDALIA,2023-09-07 21:00:00,ET,43.9,-59.7,...,,,,,,,,,9,40
125109,2023239N21274,2023,51,NA,NA,IDALIA,2023-09-08 00:00:00,ET,44.3,-59.3,...,,,,,,,,,10,35
125110,2023239N21274,2023,51,NA,NA,IDALIA,2023-09-08 03:00:00,ET,44.7,-58.8,...,,,,,,,,,11,40
125111,2023239N21274,2023,51,NA,NA,IDALIA,2023-09-08 06:00:00,ET,45.2,-58.3,...,,,,,,,,,12,40

In [12]:
# Save cleaned tracker data for future use
tracker_df.to_csv('../02_Transform/Output/cleaned_tracker_df.csv',index=False)